version: '2.1'

services:
    localstack:
        container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
        image: localstack/localstack
        ports:
            - "4566-4599:4566-4599"
            - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
        environment:
            - SERVICES=lambda,iam
            - DEBUG=1
            - DATA_DIR=/tmp/localstack/data
            - PORT_WEB_UI=8081
            - LAMBDA_EXECUTOR=docker-reuse
            - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
            - DOCKER_HOST=unix:///var/run/docker.sock
            - HOST_TMP_FOLDER=${TMPDIR}
            - LOCALSTACK_HOSTNAME=${LOCALSTACK_HOSTNAME- }
        volumes:
            - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"